<a href="https://colab.research.google.com/github/liscandeia/Codelab_Data/blob/main/ENEM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#IMPORT
import pandas as pd

In [24]:
#Configurando display de saide da tabela
pd.set_option('display.max_columns', None)

#Escolhendo colunas no arquivo dicionario de dados
#024,025, 022 verificar relação do internet e nota
#001,002 verificar relação de pais com maior nivel de graduação e nota
#006 verificar relação de situação financeira e nota
colunas = [
    'NU_ANO',
    'TP_FAIXA_ETARIA',
    'TP_SEXO',
    'TP_COR_RACA',
    'TP_ST_CONCLUSAO',
    'TP_ESCOLA',
    'TP_DEPENDENCIA_ADM_ESC',
    'TP_LOCALIZACAO_ESC',
    'CO_MUNICIPIO_ESC',
    'NU_NOTA_REDACAO',
    'NU_NOTA_LC',
    'NU_NOTA_MT',
    'NU_NOTA_CN',
    'NU_NOTA_CH',
    'Q001',
    'Q002',
    'Q006',
    'Q022',
    'Q024',
    'Q025']

enem_2021_df = pd.read_csv('/content/MICRODADOS_ENEM_2021.csv', sep=";",encoding='ISO-8859-1', usecols=colunas)
enem_2021_df.shape

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210053865474,2021,5,F,1,1,1,1,3,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3144805,Nova Lima,31,MG,0,1,1,0,NaN,881.0,892.0,NaN,NaN,574.6,472.6,NaN,NaN,BBCCECEABCEABADDAAEECBEBADADAAABABBABBACCCBBB,99999BADDEAEBACADADDAEABCEECDDBBAEADEDEABADBBA...,NaN,1.0,NaN,BEECCAEABADBCAEBAAEEDDEBBBADBCBAAEEBBBADCCBBA,ABBACAAECACDBDDADEBDDCBDCEDBEDDBBBBDCEEAADABAC...,NaN,1.0,140.0,120.0,120.0,180.0,200.0,760.0,F,F,B,B,3.0,D,A,B,C,B,A,B,A,B,A,A,A,A,B,A,A,B,A,B,B
1,210052384164,2021,12,M,1,1,1,1,11,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2704302,Maceió,27,AL,1,1,1,1,912.0,882.0,891.0,901.0,505.9,551.8,498.3,461.5,DCBCCBDBCCCCCCDDCDCCCACCABCCECCCCAADCCCBBCADE,ECCDAAEBCDACBDBDECABBEAACBCBCCCDACEABEBEBACAE,99999ACECCEEBACDABACBECBBCDBDEBDDCCCDECCDDCCCC...,CDCCBCCCDCCCCBEACEECAEABECCCDCBBCABACDAEDCCEC,1.0,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,EBAAEADBCACBBABEECBAAEEBBBADCBADBCEDDEBBCAEAB,ACABBACAEADCEADABDACDCEABDDADBEDDDEBBACCDDDCCE...,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,120.0,120.0,120.0,120.0,80.0,560.0,B,B,B,B,3.0,B,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,C,A,A,A
2,210052589243,2021,13,F,3,1,1,1,15,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3515707,Ferraz de Vasconcelos,35,SP,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,C,C,B,3.0,C,A,B,B,A,A,B,B,A,A,B,A,A,B,A,A,C,B,B,B
3,210052128335,2021,3,M,1,3,1,2,0,2,1.0,0,2304202.0,Crato,23.0,CE,2.0,1.0,1.0,2304202,Crato,23,CE,1,1,1,1,911.0,880.0,890.0,902.0,580.7,678.9,638.9,659.5,CCABBDAEDBEBEDDCAAABBDAADBDCACACEDAABCEABAEBC,CBBDABAABBAAEECEBAADADBEBCAEEBEDDEBBBADBCBEDC,ABBCA99999CDECCCBADCDBCEAEBBAAEADEEADDACAEDDAB...,EACDCEACDDDDCBDDCABADAEBACDCDDEDBBCDBECACCCCA,0.0,CDBBBCABEDEDEAAEBACCCBDABCDCBCBDECDADCDBBEEBB,BBBAAEECBBABEECEBAAEADBCACAEABEDDEBBBADBCBADC,ABBCAEAACADDCACDCADABBBBDEBBACEADCEBDDACEEDDDB...,ECCCABBDBDDDCEDDCABXEEEBABEDCEDCCAEBADBCCECDA,1.0,120.0,180.0,120.0,200.0,160.0,780.0,B,B,B,B,6.0,B,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,B,A,B,B
4,210051353021,2021,2,F,1,3,1,2,0,2,1.0,0,2311603.0,Redenção,23.0,CE,2.0,1.0,1.0,2300150,Acarape,23,CE,1,1,1,1,912.0,882.0,891.0,901.0,497.7,532.4,457.6,582.6,BABCDCCBEBCD.DEDCABCBDEDAABEDADBDBCDECCAEDBCB,CAE.ACDCAAEBBEDEBCADADEDADAACEBDABBCEABBCDEAC,99999EAACBDCBECCABADBEDADCDADDCDDECABAADEBBDAC...,ACEDEBECABDABDEECBDEEADDDDBEBCEADCCADCADEDCEB,1.0,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,EBAAEADBCACBBABEECBAAEEBBBADCBADBCEDDEBBCAEAB,ACABBACAEADCEADABDACDCEABDDADBEDDDEBBACCDDDCCE...,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,120.0,140.0,160.0,180.0,180.0,780.0,D,E,F,D,4.0,C,A,B,C,A,A,B,A,B,A,B,A,A,B,A,B,E,A,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120698,210052814880,2021,2,F,1,1,1,2,0,2,1.0,0,2304400.0,Fortaleza,23.0,CE,2.0,1.0,1.0,2304400,Fortaleza,23,CE,1,1,1,1,909.0,881.0,892.0,899.0,407.5,407.1,334.5,431.2,CADCBCCACCDBCAEBEDBABADACEDBCDACDAECACBBDCBEB,BACBAAECBCBADAEACEDACEBCAECACBABECDADAABDCEDA,CACBA99999EBBACEADAECCDADADCDEAACEDDEBACBADBEA...,DAEEDAAEABDABEADCDBBABAECEADAEACBBAABCADBCDAE,0.0,EDECABEDABCBEBACCDCBBEEBBCBDAAECDCBDCDBBBADCD,BEECCAEABADBCAEBAAEEDDEBBBADBCBAAEEBBBADCCBBA,ABBACAAECACDBDDADEBDDCBDCEDBEDDBBBBDCEEAADABAC...,EEXEBABDDCECCBCCECDCAEBADEABBDBDEDCEDCCADDCAB,1.0,140.0,120.0,120.0,120.0,40.0,540.0,H,H,F,F,3.0,C,A,C,C,B,A,B,A,B,A,A,A,A,B,A,A,C,A,A,B
120699,210052176701,2021,5,M,1,1,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3530508,Mococa,35,SP,1,1,1,1,912.0,882.0,891.0,901.0,479.1,423.4,456.8,626.1,DCECCEABECCEDDDBEDCCCAEEABCDBEECCEABCDBADCAAD,BABDECBABACABBCCACAAACBBAADBEDBACADEAEAABDBBC,EBCDD99999DBDBBDBAAEDDEAACAEBAAABDBEEDEADDAECA...,CBCEEBCCADCBEEACBBEACBBDCDCABDCCEDCAABBACECBC,0.0,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,EBAAEADBCACBBABEECBAAEEBBBADCBADBCEDDEBBCAEAB,ACABBACAEADCEADABDACDCEABDDADBEDDDEBBACCDDDCCE...,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,120.0,160.0,120.0,120.0,140.0,660.0,B,B,C,C,5.0,E,A,C,D,C,A,C,A,B,A,B,A,B,B,B,A,E,A,D,B
120700,210053002651,2021,11,F,2,2,1,1,5,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1508001,Tomé-Açu,15,PA,1,1,1,1,909.0,881.0,892.0,899.0,406.5,343.7,451.0,511.6,EDBDADACCECCBECDCCDABCDDDEEBAEABADBEECBEBABDB,ECAEAEDBBBECAEAADEECABDAEABCCAEABACBAAEDCDEEA,99999CEDDDBBBDBCADABCDBDDCDBBDCBCDCDEABADDBBDC...,BACCDAADBCCCABEADECDBBADCCECCAEBCDEDABBCDADDB,1.0,EDECABEDABCBEBACCDCBBEEBBCBDAAECDCBDCDBBBADCD,BEECCAEABADBCAEBAAEEDDEBBBADBCBAAEEBBBADCCBBA,ABBACAAECACDBDDADEBDDCBDCEDBEDDBBBBDCEEAADABAC...,EEXEBABDDCECCBCCECDCAEBADEABBDBDEDCEDCCADDCAB,1.0,100.0,120.0,120.0,120.0,120.0,580.0,B,B,A,A,2.0,B,A,B,B,A,A,B,A,A,A,A,A,A,A,A,A,B,A,A,B
120701,210053676292,2021,6,F,1,2,1,1,3,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4314407,Pelotas,43,RS,1,1,1,1,911.0,880.0,890.0,902.0,416.6,500.5,387.8,482.6,CCBBCCBBCEABAAEDBDDADACAAEBCAECCDCABBCBDADBCE,ABABCCEEBBBABCCAEAEEACBEAEEEBABDBAADDDEDCCADC,99999AACDDDCEEEBAACDDCEACCAAAEDADAEBADDACCBACC...,DAAAECBBCCEBCECDACBADAEECDDCBCCDEACBACEEAEBCA,1.0,CDBBBCABEDEDEAAEBACCCBDABCDCBCBDECDADCDBBEEBB,BBBAAEECBBABEECEBAAEADBCACAEABEDDEBBBADBCBADC,ABBCAEAACADDCACDCADABBBBDEBBACEADCEBDDACEEDDDB...,ECCCABBDBDDDCEDDCABXEEEBABEDCEDCCAEBADBCCECDA,1.0,120.0,140.0,140.0,120.0,100.0,620.0,C,E,B,B,5.0,E,A,B,C,B,A,B,A,A,A,A,A,A,B,A,A,E,A,A,B
120702,210053330747,2021,2,M,1,3,1,2,0,2,1.0,0,5200308.0,Alexânia,52.0,GO,2.0,1.0,1.0,5200308,Alexânia,52,GO,0,1,1,0,NaN,880.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
enem_2021_df.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,CO_MUNICIPIO_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q001,Q002,Q006,Q022,Q024,Q025
0,2021,5,F,1,1,1,NaN,NaN,NaN,NaN,574.6,472.6,NaN,760.0,F,F,D,B,B,B
1,2021,12,M,1,1,1,NaN,NaN,NaN,505.9,551.8,498.3,461.5,560.0,B,B,B,C,A,A
2,2021,13,F,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,C,C,C,B,B
3,2021,3,M,3,2,2,2304202.0,2.0,1.0,580.7,678.9,638.9,659.5,780.0,B,B,B,B,B,B
4,2021,2,F,3,2,2,2311603.0,2.0,1.0,497.7,532.4,457.6,582.6,780.0,D,E,C,E,B,B

In [ ]:
# isna
print(enem_2021_df.isna().sum())

# isnull
print(enem_2021_df.isnull().sum())

NU_ANO                       0
TP_FAIXA_ETARIA              0
TP_SEXO                      0
TP_COR_RACA                  0
TP_ST_CONCLUSAO              0
TP_ESCOLA                    0
CO_MUNICIPIO_ESC          9879
TP_DEPENDENCIA_ADM_ESC    9879
TP_LOCALIZACAO_ESC        9879
NU_NOTA_CN                2824
NU_NOTA_CH                2406
NU_NOTA_LC                2406
NU_NOTA_MT                2824
NU_NOTA_REDACAO           2407
Q001                         1
Q002                         1
Q006                         1
Q022                         1
Q024                         1
Q025                         1
dtype: int64
NU_ANO                       0
TP_FAIXA_ETARIA              0
TP_SEXO                      0
TP_COR_RACA                  0
TP_ST_CONCLUSAO              0
TP_ESCOLA                    0
CO_MUNICIPIO_ESC          9879
TP_DEPENDENCIA_ADM_ESC    9879
TP_LOCALIZACAO_ESC        9879
NU_NOTA_CN                2824
NU_NOTA_CH                2406
NU_NOTA_LC                2406
NU_NOTA_MT                2824
NU_NOTA_REDACAO           2407
Q001                         1
Q002                         1
Q006                         1
Q022                         1
Q024                         1
Q025                         1
dtype: int64

In [ ]:
#Tratamento dos dados
#Excluindo os nulos em qualquer uma das provas pra não afetar a analise
enem_2021_df.dropna(subset=['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO'], inplace=True)
enem_2021_df.head()
enem_2021_df.shape
#Excluindo os nulos de q001...q0025 pois é só uma linha e não vai afetar no banco
enem_2021_df.dropna(subset=['Q001','Q002','Q006', 'Q022', 'Q024', 'Q025'], inplace=True)
enem_2021_df.shape
print(enem_2021_df.isna().sum())
print(enem_2021_df.isnull().sum())

(9935, 20)

In [ ]:
#Excluindo os nulos de q001...q0025 pois é só uma linha e não vai afetar no banco
enem_2021_df.dropna(subset=['Q001','Q002','Q006', 'Q022', 'Q024', 'Q025'], inplace=True)
enem_2021_df.shape

(9935, 20)

In [ ]:
# verificando
print(enem_2021_df.isna().sum())
print(enem_2021_df.isnull().sum())

NU_ANO                       0
TP_FAIXA_ETARIA              0
TP_SEXO                      0
TP_COR_RACA                  0
TP_ST_CONCLUSAO              0
TP_ESCOLA                    0
CO_MUNICIPIO_ESC          7416
TP_DEPENDENCIA_ADM_ESC    7416
TP_LOCALIZACAO_ESC        7416
NU_NOTA_CN                   0
NU_NOTA_CH                   0
NU_NOTA_LC                   0
NU_NOTA_MT                   0
NU_NOTA_REDACAO              0
Q001                         0
Q002                         0
Q006                         0
Q022                         0
Q024                         0
Q025                         0
dtype: int64
NU_ANO                       0
TP_FAIXA_ETARIA              0
TP_SEXO                      0
TP_COR_RACA                  0
TP_ST_CONCLUSAO              0
TP_ESCOLA                    0
CO_MUNICIPIO_ESC          7416
TP_DEPENDENCIA_ADM_ESC    7416
TP_LOCALIZACAO_ESC        7416
NU_NOTA_CN                   0
NU_NOTA_CH                   0
NU_NOTA_LC                   0
NU_NOTA_MT                   0
NU_NOTA_REDACAO              0
Q001                         0
Q002                         0
Q006                         0
Q022                         0
Q024                         0
Q025                         0
dtype: int64

In [ ]:
#Transformando para leitura
enem_2021_df['TP_FAIXA_ETARIA'] = enem_2021_df['TP_FAIXA_ETARIA'].map({
    1: 'Menor que 17 anos',
    2: '17 anos',
    3: '18 anos',
    4: '19 anos',
    5: '20 anos',
    6: '21 anos',
    7: '22 anos',
    8: '23 anos',
    9: '24 anos',
    10: '25 anos',
    11: 'entre 26 e 30 anos',
    12: 'entre 31 e 35 anos',
    13: 'entre 36 e 40 anos',
    14: 'entre 41 e 45 anos',
    15: 'entre 46 e 50 anos',
    16: 'entre 51 e 55 anos',
    17: 'entre 56 e 60 anos',
    18: 'entre 61 e 65 anos',
    19: 'entre 66 e 70 anos',
    20: 'mais de 70 anos'

})

enem_2021_df.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,CO_MUNICIPIO_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q001,Q002,Q006,Q022,Q024,Q025
1,2021,entre 31 e 35 anos,M,1,1,1,NaN,NaN,NaN,505.9,551.8,498.3,461.5,560.0,B,B,B,C,A,A
3,2021,18 anos,M,3,2,2,2304202.0,2.0,1.0,580.7,678.9,638.9,659.5,780.0,B,B,B,B,B,B
4,2021,17 anos,F,3,2,2,2311603.0,2.0,1.0,497.7,532.4,457.6,582.6,780.0,D,E,C,E,B,B
8,2021,23 anos,F,3,2,2,NaN,NaN,NaN,487.4,476.5,450.7,493.4,520.0,B,B,B,B,A,B
9,2021,19 anos,F,3,2,2,NaN,NaN,NaN,507.6,539.2,494.6,413.3,380.0,D,D,B,C,A,B

In [ ]:
mapa_regioes = {
    '1': 'Norte',
    '2': 'Nordeste',
    '3': 'Sudeste',
    '4': 'Sul',
    '5': 'Centro-Oeste'
}
mapa_uf = {
    '11': 'Rondônia',
    '12': 'Acre',
    '13': 'Amazonas',
    '14': 'Roraima',
    '15': 'Pará',
    '16': 'Amapá',
    '17': 'Tocantins',
    '21': 'Maranhão',
    '22': 'Piauí',
    '23': 'Ceará',
    '24': 'Rio Grande do Norte',
    '25': 'Paraíba',
    '26': 'Pernambuco',
    '27': 'Alagoas',
    '28': 'Sergipe',
    '29': 'Bahia',
    '31': 'Minas Gerais',
    '32': 'Espírito Santo',
    '33': 'Rio de Janeiro',
    '35': 'São Paulo',
    '41': 'Paraná',
    '42': 'Santa Catarina',
    '43': 'Rio Grande do Sul',
    '50': 'Mato Grosso do Sul',
    '51': 'Mato Grosso',
    '52': 'Goiás',
    '53': 'Distrito Federal'
}

enem_2021_df['CO_REGIAO_ESC'] = enem_2021_df['CO_MUNICIPIO_ESC'].astype(str).apply(lambda codigo_municipio : codigo_municipio[0])
enem_2021_df['CO_REGIAO_ESC'] = enem_2021_df['CO_REGIAO_ESC'].map(mapa_regioes)
enem_2021_df.head()
enem_2021_df['CO_UF_ESC'] = enem_2021_df['CO_MUNICIPIO_ESC'].astype(str).apply(lambda codigo_municipio : codigo_municipio[:2])
enem_2021_df['CO_UF_ESC'] = enem_2021_df['CO_UF_ESC'].map(mapa_uf)
enem_2021_df.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,CO_MUNICIPIO_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q001,Q002,Q006,Q022,Q024,Q025,CO_REGIAO_ESC,CO_UF_ESC
1,2021,entre 31 e 35 anos,M,1,1,1,NaN,NaN,NaN,505.9,551.8,498.3,461.5,560.0,B,B,B,C,A,A,NaN,NaN
3,2021,18 anos,M,3,2,2,2304202.0,2.0,1.0,580.7,678.9,638.9,659.5,780.0,B,B,B,B,B,B,Nordeste,Ceará
4,2021,17 anos,F,3,2,2,2311603.0,2.0,1.0,497.7,532.4,457.6,582.6,780.0,D,E,C,E,B,B,Nordeste,Ceará
8,2021,23 anos,F,3,2,2,NaN,NaN,NaN,487.4,476.5,450.7,493.4,520.0,B,B,B,B,A,B,NaN,NaN
9,2021,19 anos,F,3,2,2,NaN,NaN,NaN,507.6,539.2,494.6,413.3,380.0,D,D,B,C,A,B,NaN,NaN

In [ ]:
enem_2021_df['TP_COR_RACA'] = enem_2021_df['TP_COR_RACA'].map({0:'NA', 1:'Branca', 2:'Preta', 3:'Parda', 4:'Amarela', 5:'Indigena'})

In [ ]:
enem_2021_df['Q025'] = enem_2021_df['Q025'].map({'A':'Não', 'B':'Sim'})

In [ ]:
enem_2021_df['Q001'] = enem_2021_df['Q001'].map({
                            'A':'Nunca estudou',
                            'B':'Não completou EF',
                            'C':'Não completou EF',
                            'D':'Não completou EM',
                            'E':'Não completou ES',
                            'F':'Graduada',
                            'G':'Pós-graduada',
                            'H':'Não sabe'
                            })
enem_2021_df['Q002'] = enem_2021_df['Q002'].map({
                            'A':'Nunca estudou',
                            'B':'Não completou EF',
                            'C':'Não completou EF',
                            'D':'Não completou EM',
                            'E':'Não completou ES',
                            'F':'Graduada',
                            'G':'Pós-graduada',
                            'H':'Não sabe'
                            })

In [ ]:
enem_2021_df['Q006'] = enem_2021_df['Q006'].map({'A':'Nenhuma renda',
                            'B':'Até 1.045,00',
                            'C':'Até 1.567,50',
                            'D':'Até 2.090,00',
                            'E':'Até 2.612,50',
                            'F':'Até 3.135,00',
                            'G':'Até 4.180,00',
                            'H':'Até 5.225,00',
                            'I':'Até 6.270,00',
                            'J':'Até 7.315,00',
                            'K':'Até 8.360,00',
                            'L':'Até 9.405,00',
                            'M':'Até 10.450,00',
                            'N':'Até 12.540,00',
                            'O':'Até 15.675,00',
                            'P':'Até 20.900,00',
                            'Q':'Acima de 20.900,00'
                            })

In [ ]:
enem_2021_df.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,CO_MUNICIPIO_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q001,Q002,Q006,Q022,Q024,Q025,CO_REGIAO_ESC,CO_UF_ESC
1,2021,entre 31 e 35 anos,M,Branca,1,1,NaN,NaN,NaN,505.9,551.8,498.3,461.5,560.0,Não completou EF,Não completou EF,"Até 1.045,00",C,A,Não,NaN,NaN
3,2021,18 anos,M,Parda,2,2,2304202.0,2.0,1.0,580.7,678.9,638.9,659.5,780.0,Não completou EF,Não completou EF,"Até 1.045,00",B,B,Sim,Nordeste,Ceará
4,2021,17 anos,F,Parda,2,2,2311603.0,2.0,1.0,497.7,532.4,457.6,582.6,780.0,Não completou EM,Não completou ES,"Até 1.567,50",E,B,Sim,Nordeste,Ceará
8,2021,23 anos,F,Parda,2,2,NaN,NaN,NaN,487.4,476.5,450.7,493.4,520.0,Não completou EF,Não completou EF,"Até 1.045,00",B,A,Sim,NaN,NaN
9,2021,19 anos,F,Parda,2,2,NaN,NaN,NaN,507.6,539.2,494.6,413.3,380.0,Não completou EM,Não completou EM,"Até 1.045,00",C,A,Sim,NaN,NaN

In [ ]:
enem_2021_df['TP_ESCOLA'] = enem_2021_df['TP_ESCOLA'].map({
    1: 'Não Respondeu',
    2: 'Pública',
    3: 'Privada'
    })
enem_2021_df.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,CO_MUNICIPIO_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q001,Q002,Q006,Q022,Q024,Q025,CO_REGIAO_ESC,CO_UF_ESC
1,2021,entre 31 e 35 anos,M,Branca,1,Não Respondeu,NaN,NaN,NaN,505.9,551.8,498.3,461.5,560.0,Não completou EF,Não completou EF,"Até 1.045,00",C,A,Não,NaN,NaN
3,2021,18 anos,M,Parda,2,Pública,2304202.0,2.0,1.0,580.7,678.9,638.9,659.5,780.0,Não completou EF,Não completou EF,"Até 1.045,00",B,B,Sim,Nordeste,Ceará
4,2021,17 anos,F,Parda,2,Pública,2311603.0,2.0,1.0,497.7,532.4,457.6,582.6,780.0,Não completou EM,Não completou ES,"Até 1.567,50",E,B,Sim,Nordeste,Ceará
8,2021,23 anos,F,Parda,2,Pública,NaN,NaN,NaN,487.4,476.5,450.7,493.4,520.0,Não completou EF,Não completou EF,"Até 1.045,00",B,A,Sim,NaN,NaN
9,2021,19 anos,F,Parda,2,Pública,NaN,NaN,NaN,507.6,539.2,494.6,413.3,380.0,Não completou EM,Não completou EM,"Até 1.045,00",C,A,Sim,NaN,NaN

In [ ]:

enem_2021_df['TP_DEPENDENCIA_ADM_ESC'] = enem_2021_df['TP_DEPENDENCIA_ADM_ESC'].map({ 1: 'Federal',2:'Estadual',3:'Municipal',4:'Privada'})

In [ ]:
enem_2021_df['TP_LOCALIZACAO_ESC'] = enem_2021_df['TP_LOCALIZACAO_ESC'].map({1:'Urbana',2:'Rural'})

In [ ]:
enem_2021_df.drop(columns=['CO_MUNICIPIO_ESC', 'Q022', 'Q024', 'TP_ST_CONCLUSAO'], inplace=True)

In [ ]:
enem_2021_df.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ESCOLA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q001,Q002,Q006,Q025,CO_REGIAO_ESC,CO_UF_ESC
1,2021,entre 31 e 35 anos,M,Branca,Não Respondeu,NaN,NaN,505.9,551.8,498.3,461.5,560.0,Não completou EF,Não completou EF,"Até 1.045,00",Não,NaN,NaN
3,2021,18 anos,M,Parda,Pública,Estadual,Urbana,580.7,678.9,638.9,659.5,780.0,Não completou EF,Não completou EF,"Até 1.045,00",Sim,Nordeste,Ceará
4,2021,17 anos,F,Parda,Pública,Estadual,Urbana,497.7,532.4,457.6,582.6,780.0,Não completou EM,Não completou ES,"Até 1.567,50",Sim,Nordeste,Ceará
8,2021,23 anos,F,Parda,Pública,NaN,NaN,487.4,476.5,450.7,493.4,520.0,Não completou EF,Não completou EF,"Até 1.045,00",Sim,NaN,NaN
9,2021,19 anos,F,Parda,Pública,NaN,NaN,507.6,539.2,494.6,413.3,380.0,Não completou EM,Não completou EM,"Até 1.045,00",Sim,NaN,NaN

In [ ]:
enem_2021_df['TP_SEXO'] = enem_2021_df['TP_SEXO'].map({'F':'Feminino','M':'Masculino'})

In [ ]:
enem_2021_df.shape

(9935, 18)

In [ ]:
enem_2021_df.to_csv('enem_2021_tratado.csv', index=False)

In [ ]:
enem_2021_df.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_COR_RACA,TP_ESCOLA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q001,Q002,Q006,Q025,CO_REGIAO_ESC,CO_UF_ESC
1,2021,entre 31 e 35 anos,Masculino,Branca,Não Respondeu,NaN,NaN,505.9,551.8,498.3,461.5,560.0,Não completou EF,Não completou EF,"Até 1.045,00",Não,NaN,NaN
3,2021,18 anos,Masculino,Parda,Pública,Estadual,Urbana,580.7,678.9,638.9,659.5,780.0,Não completou EF,Não completou EF,"Até 1.045,00",Sim,Nordeste,Ceará
4,2021,17 anos,Feminino,Parda,Pública,Estadual,Urbana,497.7,532.4,457.6,582.6,780.0,Não completou EM,Não completou ES,"Até 1.567,50",Sim,Nordeste,Ceará
8,2021,23 anos,Feminino,Parda,Pública,NaN,NaN,487.4,476.5,450.7,493.4,520.0,Não completou EF,Não completou EF,"Até 1.045,00",Sim,NaN,NaN
9,2021,19 anos,Feminino,Parda,Pública,NaN,NaN,507.6,539.2,494.6,413.3,380.0,Não completou EM,Não completou EM,"Até 1.045,00",Sim,NaN,NaN